[ubuntu_vm]
10.244.0.15

[ubuntu_vm:vars]
ansible_user=root

[windows]
# 10.244.0.20          # ← replace with your Windows Server IP

[windows:vars]
ansible_user=Administrator
ansible_password=YourPassword          # ← replace or use vault
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_winrm_server_cert_validation=ignore
ansible_port=5986
